### ISSUE TITLE
What do you think could be my mistake?

### ISSUE THREAD

**Issue by JokoKenguru** [TeamFightTacticsBots/Alune#14]
https://youtu.be/MmbsFlAJUPY

**Comment by JokoKenguru** [comment]
logs
2024-05-21 02:48:36.301 | INFO     | __main__:check_version:380 - You are running the latest version.
2024-05-21 02:48:36.303 | INFO     | alune.adb:_connect_to_device:73 - Attempting to connect to ADB session with device localhost:5555
2024-05-21 02:48:38.310 | DEBUG    | __main__:main:415 - ADB is connected, checking phone and app details
2024-05-21 02:48:38.310 | DEBUG    | __main__:check_phone_preconditions:325 - Checking screen size
2024-05-21 02:48:38.319 | DEBUG    | __main__:check_phone_preconditions:334 - Checking screen density
2024-05-21 02:48:38.328 | DEBUG    | __main__:check_phone_preconditions:340 - Checking memory
2024-05-21 02:48:38.333 | DEBUG    | __main__:check_phone_preconditions:344 - Checking if TFT is installed
2024-05-21 02:48:38.342 | DEBUG    | __main__:check_phone_preconditions:348 - Checking TFT app version

**Comment by akshualy** [comment]
It seems the connection to scrape the TFT app version from Google Play was forcibly closed. There's nothing much we can do here, except try again later. I've pushed a catch for this in the [latest release](https://github.com/TeamFightTacticsBots/Alune/releases/latest).

**Comment by JokoKenguru** [comment]
And when will the opportunity to choose your own assembly be available?)

**Comment by JokoKenguru** [comment]
I noticed another point, after losing, he quits the game.. but it doesn't do anything on the table of places

**Comment by akshualy** [comment]
> And when will the opportunity to choose your own assembly be available?)
We won't implement something like defining every unit to buy in the config, but using the team planner is something that has been suggested and relatively easy to implement. 

> And I also wanted to clarify, is it necessary to install the English version of the language?
The screenshots were made in the English version, but it shouldn't be necessary at the moment as I tried to make sure not to include any text in the recognition screenshots. Feel free to tell me if it breaks using a different language.

> but it doesn't do anything on the table of places
It should click the "Play again" button, I'd need a screenshot to see if anything is blocking the recognition. (Please remember to blur any usernames for your own protection)

**Comment by JokoKenguru** [comment]
> Feel free to tell me if it breaks using a different language.
Thank you, then I will still use the translator) And it would also be cool for him to recognize the picture of the "heavenly ones" faster. Then it would be possible to run it in the mode with a "set of points". Since there is no event right now)

**Comment by akshualy** [comment]
Sadly there is no speed improvement that i can think of, ADB itself is quite slow and python isn't the fastest either. But saving up to 50 gold before spending it is something I already [have planned](https://github.com/TeamFightTacticsBots/Alune/wiki/Features#planned).

**Comment by santahashi** [comment]
@akshualy 

Dear, 

I have had the same problem and can't seem to fix it. Using 0.1.2 

Is that because of the new TFT version? currently 14.12

2024-06-13 07:20:26.337 | INFO     | __main__:check_version:388 - You are running the latest version.
2024-06-13 07:20:26.340 | INFO     | alune.adb:_connect_to_device:73 - Attempting to connect to ADB session with device localhost:5555
2024-06-13 07:20:28.349 | DEBUG    | __main__:main:423 - ADB is connected, checking phone and app details
2024-06-13 07:20:28.349 | DEBUG    | __main__:check_phone_preconditions:326 - Checking screen size
2024-06-13 07:20:28.356 | DEBUG    | __main__:check_phone_preconditions:335 - Checking screen density
2024-06-13 07:20:28.362 | DEBUG    | __main__:check_phone_preconditions:341 - Checking memory
2024-06-13 07:20:28.365 | DEBUG    | __main__:check_phone_preconditions:345 - Checking if TFT is installed
2024-06-13 07:20:28.371 | DEBUG    | __main__:check_phone_preconditions:349 - Checking TFT app version

**Comment by akshualy** [comment]
@santahashi Quick question, are you by chance from russia? If so, could you try again by using a VPN (if that's possible, I am not up to date on what Russia is and isn't allowed to do.) It may be related to the sanctions they made against russia 2-ish years ago. I might need to look into an alternative way if this is the case.

**Comment by santahashi** [comment]
> @santahashi Quick question, are you by chance from russia? If so, could you try again by using a VPN (if that's possible, I am not up to date on what Russia is and isn't allowed to do.) It may be related to the sanctions they made against russia 2-ish years ago. I might need to look into an alternative way if this is the case.

Dear akshualy, 

Thank you for your reply, but no, I am not from Russia. I'm from Vietnam, using this apk: https://apkpure.com/vn/%C4%91%E1%BA%A5u-tr%C6%B0%E1%BB%9Dng-ch%C3%A2n-l%C3%BD-lmht-teamf/com.riotgames.league.teamfighttacticsvn

**Comment by santahashi** [comment]
Okay so I found the problem. 

Its relating to the `self.tft_package_name` in adb.py . Just change it if your TFT are from different regions.

**Comment by akshualy** [comment]
Ahh okay, got it, thanks for investigating it!

**Comment by JokoKenguru** [comment]
problems
https://youtu.be/XiGYVG_eLw4

**Comment by JokoKenguru** [comment]
A new set No. 12 has been released. Will there be an assembly icon under it? the bot is already a job, of course, but.. suddenly)

**Comment by JokoKenguru** [comment]
There's a new mode added, maybe you can add a selection of it? And also.. there you can make an assembly, for example, "imp"

**Comment by JokoKenguru** [comment]
I checked it out.. even if you do nothing in the game and give up at stage 3-1, you still get experience

**Comment by JokoKenguru** [comment]
@akshualy

**Comment by akshualy** [comment]
> I checked it out.. even if you do nothing in the game and give up at stage 3-1, you still get experience

Depends on TFT pass or Event experience; TFT pass experience is per game and event experience is per minute played, double for wins.

I'm not home at the moment to look into the new mode, sorry.

**Comment by RomeoAlphaEkko** [comment]
Yes there is a grind pass too for 5.5

But they have a different trait set

**Comment by JokoKenguru** [comment]
it would be cool if you had time to make a "switch" for this mode) @akshualy

**Comment by JokoKenguru** [comment]
![image](https://github.com/user-attachments/assets/85c22604-679b-4fe5-a35d-999eb14d7a53)
And at all.. What I wanted to say.. it is already impossible to find the game, I tried both night and day as now, the timer passes in 10 minutes to no avail ((

**Comment by JokoKenguru** [comment]
need set13

**Comment by JokoKenguru** [comment]
2024-12-03 01:56:12.775 | INFO     | __main__:check_version:510 - You are running the latest version.
2024-12-03 01:56:12.899 | INFO     | alune.adb:_connect_to_device:105 - Attempting to connect to ADB session with device localhost:5555
2024-12-03 01:56:14.904 | DEBUG    | __main__:main:547 - ADB is connected, checking phone and app details
2024-12-03 01:56:14.905 | DEBUG    | __main__:check_phone_preconditions:448 - Checking screen size
2024-12-03 01:56:23.906 | ERROR    | __main__:<module>:622 - Reading from localhost:5555 timed out (9 seconds)
Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 107, in bulk_read

  File "asyncio\streams.py", line 713, in read

  File "asyncio\streams.py", line 545, in _wait_for_data

asyncio.exceptions.CancelledError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 106, in bulk_read

  File "asyncio\timeouts.py", line 115, in __aexit__

TimeoutError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

> File "main.py", line 618, in <module>

  File "asyncio\runners.py", line 194, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 687, in run_until_complete

  File "main.py", line 548, in main

  File "main.py", line 449, in check_phone_preconditions

  File "alune\adb.py", line 139, in get_screen_size

  File "adb_shell\adb_device_async.py", line 881, in shell

  File "adb_shell\adb_device_async.py", line 749, in _service

  File "adb_shell\adb_device_async.py", line 1327, in _streaming_command

  File "adb_shell\adb_device_async.py", line 1225, in _open

  File "adb_shell\adb_device_async.py", line 376, in read

  File "adb_shell\adb_device_async.py", line 523, in _read_packet_from_device

  File "adb_shell\adb_device_async.py", line 479, in _read_bytes_from_device

  File "adb_shell\transport\tcp_transport_async.py", line 110, in bulk_read

adb_shell.exceptions.TcpTimeoutException: Reading from localhost:5555 timed out (9 seconds)
2024-12-03 01:56:23.920 | WARNING  | __main__:<module>:623 - Due to an error, we are exiting Alune in 10 seconds. You can find all logs in alune-output/logs.
