### ISSUE TITLE
Stopped working (crash due to traceback)

### ISSUE THREAD

**Issue by Dropeza** [TeamFightTacticsBots/Alune#77]
Hello, I'm using bluestacks as the emulator (followed all the steps on the wiki). Alune was working fine for me for weeks, then stopped working yesterday. Log file attached, I tried deleting the output folder and the executable and downloading it again but it didn't fix the issue. I did not mess with the config file either. 

2024-10-29 20:30:18.379 | INFO     | __main__:check_version:492 - You are running the latest version.
2024-10-29 20:30:18.454 | INFO     | alune.adb:_connect_to_device:105 - Attempting to connect to ADB session with device localhost:5555
2024-10-29 20:30:29.459 | ERROR    | __main__:<module>:604 - Reading from localhost:5555 timed out (9 seconds)
Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 107, in bulk_read

  File "asyncio\streams.py", line 713, in read

  File "asyncio\streams.py", line 545, in _wait_for_data

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 106, in bulk_read

  File "async_timeout\__init__.py", line 141, in __aexit__

  File "async_timeout\__init__.py", line 228, in _do_exit

TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

> File "main.py", line 600, in <module>

  File "asyncio\runners.py", line 194, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 687, in run_until_complete

  File "main.py", line 524, in main

  File "alune\adb.py", line 49, in load

  File "alune\adb.py", line 107, in _connect_to_device

  File "adb_shell\adb_device_async.py", line 714, in connect

  File "adb_shell\adb_device_async.py", line 265, in connect

  File "adb_shell\adb_device_async.py", line 445, in _read_expected_packet_from_device

  File "adb_shell\adb_device_async.py", line 523, in _read_packet_from_device

  File "adb_shell\adb_device_async.py", line 479, in _read_bytes_from_device

  File "adb_shell\transport\tcp_transport_async.py", line 110, in bulk_read

adb_shell.exceptions.TcpTimeoutException: Reading from localhost:5555 timed out (9 seconds)
2024-10-29 20:30:29.473 | WARNING  | __main__:<module>:605 - Due to an error, we are exiting Alune in 10 seconds. You can find all logs in alune-output/logs.

**Comment by akshualy** [comment]
Hello, please double check that you have enabled ADB in BlueStacks. A detailed info on how to check that can be found here: https://github.com/TeamFightTacticsBots/Alune/wiki/Emulators#configuration

**Comment by Dropeza** [comment]
It was enabled and had the correct port (5555), I ran Alune again just to double check and it crashed again. Then I unchecked the ADB option, restarted Bluestacks and re-enabled it. Seems like a Bluestacks issue, thank you for your guidance.
