### ISSUE TITLE
What should I do to fix the error?

### ISSUE THREAD

**Issue by 1m2p3** [TeamFightTacticsBots/Alune#96]
When I followed exactly what was written in the manual and installed tft on the bluestack 5 emulator and ran alune.exe, I got the following error statement. How do I fix this?

_________________________________________________________________________________________________________
2024-12-12 06:07:23.512 | INFO     | __main__:check_version:510 - You are running the latest version.
2024-12-12 06:07:23.514 | INFO     | alune.adb:_connect_to_device:105 - Attempting to connect to ADB session with device localhost:5555
2024-12-12 06:07:34.518 | ERROR    | __main__:<module>:622 - Reading from localhost:5555 timed out (9 seconds)
Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 107, in bulk_read

  File "asyncio\streams.py", line 713, in read

  File "asyncio\streams.py", line 545, in _wait_for_data

asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "adb_shell\transport\tcp_transport_async.py", line 106, in bulk_read

  File "asyncio\timeouts.py", line 115, in __aexit__

TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

> File "main.py", line 618, in <module>
    logger.warning("Bot will queue a new game when in lobby!")
    │      └ <function Logger.warning at 0x000002B99057B1A0>
    └ <loguru.logger handlers=[(id=1, level=10, sink='C:\Users\kmg12\OneDrive\Wallpaper\New Folder\Alune\alune-output\logs/{time}.log'), (id=...

  File "asyncio\runners.py", line 194, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 687, in run_until_complete

  File "main.py", line 542, in main
    await check_version()
          └ <function check_version at 0x000002B9A845D440>

  File "alune\adb.py", line 49, in load
    self._default_port = config.get_adb_port()
    └ <alune.adb.ADB object at 0x000002B9A8444D70>

  File "alune\adb.py", line 107, in _connect_to_device
    return conn.laddr.port

  File "adb_shell\adb_device_async.py", line 714, in connect

  File "adb_shell\adb_device_async.py", line 265, in connect

  File "adb_shell\adb_device_async.py", line 445, in _read_expected_packet_from_device

  File "adb_shell\adb_device_async.py", line 523, in _read_packet_from_device

  File "adb_shell\adb_device_async.py", line 479, in _read_bytes_from_device

  File "adb_shell\transport\tcp_transport_async.py", line 110, in bulk_read

adb_shell.exceptions.TcpTimeoutException: Reading from localhost:5555 timed out (9 seconds)
2024-12-12 06:07:34.523 | WARNING  | __main__:<module>:623 - Due to an error, we are exiting Alune in 10 seconds. You can find all logs in alune-output/logs.

**Comment by akshualy** [comment]
Have you followed the steps to enable ADB in BlueStacks? You have to specifically flip a button in the settings.

**Comment by 1m2p3** [comment]
> Have you followed the steps to enable ADB in BlueStacks? You have to specifically flip a button in the settings.

Thank you, as you explained, I activated ADB now and ran Alune, and the error is gone.
But now the bot is not working.

"The bot will play out games. This is recommended for passes that get experience for play time, like the event passes."
There has been no response since this message

**Comment by akshualy** [comment]
You can either enable DEBUG in the alune-output/config.yaml file, or check the log files in alune-output/logs. They should give you more of a hint as to where the bot is stuck.

**Comment by 1m2p3** [comment]
> alune-output/config.yaml 파일에서 DEBUG를 활성화하거나 alune-output/logs에서 로그 파일을 확인할 수 있습니다. 봇이 어디에 갇혔는지에 대한 힌트를 더 많이 제공할 것입니다.

Thanks to reply again!! By uninstalling Bulestack and installing LDPlayer, bot worked fine. Maybe it was emulator's problem. But after the bot plays the first game, it doesn't start the next game on the result screen. I've activated DEBUG and there's no message from the console.

**Comment by Kyrluckechuck** [comment]
@1m2p3 as a workaround for now you can revert to non-screen recording which is slower but more reliable currently
https://github.com/TeamFightTacticsBots/Alune/issues/95#issuecomment-2536062420

Set this:
```yaml
screen_record:
  enabled: false
```

**Comment by 1m2p3** [comment]
> @1m2p3 as a workaround for now you can revert to non-screen recording which is slower but more reliable currently [#95 (comment)](https://github.com/TeamFightTacticsBots/Alune/issues/95#issuecomment-2536062420)
> 
> Set this:
> 
> ```yaml
> screen_record:
>   enabled: false
> ```

Oh thank you but I cant find screen record settings in config.yaml. Where can I set this? Can I just add it to config.yaml?
